services:
  stencil:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Surge:/app/Surge
      - ./Stash:/app/Stash
    restart: unless-stopped
